version: '3.8'

services:
  card-service:
    build: .
    container_name: card-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped

