version: '3.8'

services:
  card-service:
    build: .
    container_name: card-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
