server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<path>.*),/$\{path}
        - id: test-node
          uri: lb://test-node
          predicates:
            - Path=/nodejs/**
          filters:
            - RewritePath=/nodejs/(?<path>.*),/$\{path}
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/cards/**
          filters:
            - RewritePath=/cards/(?<path>.*), /api/cards/${path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /api/user/${path}
        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/transactions/**
          filters:
            - RewritePath=/transactions/(?<path>.*), /api/user/${path}
        #        - id: admin-service
        #          uri: lb://adminTask-service
        #          predicates:
        #            - Path=/adminTask/**
        #          filters:
        #            - RewritePath=/adminTask/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*),/$\{path}/v3/api-docs

springdoc:
  swagger-ui:
  urls:
    - name: account
      url: /v3/api-docs/account

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
