version: "3.7"
name: banking-microservice
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"
    networks:
      - banking_network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15673:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking_network
  config-service:
    container_name: config-service
    image: banking/config-server:1.1-SNAPSHOT
    ports:
      - "8088:8088"
    healthcheck:
       test: curl --fail http://localhost:8088/enrollment/docker  || exit 1
       interval: 15s
       timeout: 5s
       retries: 10
    networks:
      - banking_network
  discovery-service:
    container_name: discovery-service
    image: banking/discovery-service:1.1-SNAPSHOT
    ports:
      - "8761:8761"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    healthcheck:
      test: curl --fail http://localhost:8761/eureka/v2/apps || exit 1
      interval: 15s
      timeout: 5s
      retries: 10
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - banking_network
  pgsql-account:
    image: postgres:15-alpine
    container_name: pgsql-account
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: banking_db
      POSTGRES_MAX_CONNECTIONS: 100
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/account.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking_network
  account-service:
     container_name: account-service
     image: banking/account-service:1.0-SNAPSHOT
     ports:
       - "8080"
     depends_on:
       discovery-service:
         condition: service_healthy
     links:
       - config-service
       - discovery-service
       - zipkin
       - pgsql-account
     environment:
       SPRING_PROFILES_ACTIVE: docker
     networks:
       - banking_network
  test-node:
    container_name: test-node
    image: banking/test-node:1.1-SNAPSHOT
    build:
      context: ./test-node       # relative path to your Node module
      dockerfile: Dockerfile     # ensure this file exists in test-node/
    ports:
      - "3000"              # adjust if your app listens on a different port
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    environment:
      NODE_ENV: production
    networks:
      - banking_network
# Below are some sample services for the banking application.
  # mysql-Enrollment:
  #     image: mysql:8.3.0
  #     container_name: mysql-Enrollment
  #     ports:
  #       - "3307:3306"
  #     environment:
  #       - MYSQL_ROOT_PASSWORD=root
  #       - MYSQL_DATABASE=enrollment_service
  #     volumes:
  #       - ./mysql/enrollment_data:/var/lib/mysql
  #       - ./docker/mysql/init_enrollment.sql:/docker-entrypoint-initdb.d/init.sql
  #     healthcheck:
  #       test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
  #       interval: 15s
  #       timeout: 5s
  #       retries: 10
  #     networks:
  #       - banking_network
  # admin-service:
  #   image: banking/admin-service:1.2-SNAPSHOT
  #   ports:
  #     - "8080"
  #   depends_on:
  #     discovery-service:
  #       condition: service_healthy
  #   links:
  #     - config-service
  #     - discovery-service
  #     - zipkin
  #     - mysql-Enrollment
  #     - mysql-Order
  #     - mysql-User
  #     - mongo-Course
  #     - mysql-Content
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker
  #   networks:
  #     - banking_network
  gateway-service:
    container_name: gateway-service
    image: banking/gateway-service:0.0.1-SNAPSHOT
    ports:
      - "8060:8060"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - config-service
      - discovery-service
      - zipkin
      - pgsql-account
      - account-service
      - test-node
      # - mysql-Enrollment
      # - user-service
      # - auth-service
    networks:
      - banking_network

networks:
  banking_network:
    driver: bridge

volumes:
  postgres-data: