name: Smart Bank System – CI Pipeline (Push to Docker Hub)

on:
  push:
    branches: 
      - main
      - feat/rewrite
  pull_request:
    branches: 
      - main
      - feat/rewrite

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      # --- API Gateway ---
      - name: Build & Push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./_api-gateway
          push: true
          tags: ${{ env.DOCKER_USER }}/api-gateway:latest

      # --- Account Service ---
      - name: Build & Push Account Service
        uses: docker/build-push-action@v4
        with:
          context: ./account-service
          push: true
          tags: ${{ env.DOCKER_USER }}/account-service:latest

      # --- Transaction Service ---
      - name: Build & Push Transaction Service
        uses: docker/build-push-action@v4
        with:
          context: ./transaction-service
          push: true
          tags: ${{ env.DOCKER_USER }}/transaction-service:latest

      # --- Card Service ---
      - name: Build & Push Card Service
        uses: docker/build-push-action@v4
        with:
          context: ./card-service
          push: true
          tags: ${{ env.DOCKER_USER }}/card-service:latest

      # --- User Service ---
      - name: Build & Push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          push: true
          tags: ${{ env.DOCKER_USER }}/user-service:latest
